### PR TITLE
Template fetch helper

### PR DESCRIPTION
**Pull request by hairmare**
This script helps fetch templates into a local file from a remote zabbix api endpoint.

If no arguments are given the script outputs a list of all available templates.

## Usage
```bash
rabe-zabbix [command_options] [FILENAME]
```

## Options
  --template=[name], -t [name]  Name of template to search, multiple templates allowed
  --insecure, -k                Ignore unauthorized TLS certs
  --make-update                 Call make update after a successful export
  --config-get [key]            Get config value for key
  --config-set [key] [val]      Set config value key to val
  --help, -h                    Print this help

The script will prompt for some configuration options on first run. These get persisted to 
the disk for later use and they may be queried/changed with the --config-get and --config-set options.

###  Export a single template to a file.

```
rabe-zabbix --template='Template App ntpd active' app/chrony/Template_App_chrony_active.xml
```
###  Export multiple templates to a single file.

```
rabe-zabbix \
      -t 'Template App ntpd Common active' \
      -t 'Template App ntpd Client active' \
    -t 'Template App ntpd Server active' app/ntpd/Template_App_ntpd_active.xml
```
###  List all templates
```
rabe-zabbix
```
###  Set API endpoint to localhost.
``` 
rabe-zabbix --config-set api http://localhost/zabbix/api_jsonrpc.php
```
## Install
README.md has infos on how to install this locally.

```
npm install
./helper/rabe-zabbix --help
```

### CODE REVIEW

**Comment by paraenggu** [comment]
After the first configuration run, I get the following `TypeError` while trying to execute the script:
```bash 
./rabe-zabbix
```
```
⠙ Logging in to Zabbix/home/chrigu/repos/rabe/rabe-zabbix/node_modules/zabbix-api/index.js:110
        fn(new Error("HTTP request error. message: " + err + ". statusCode: " + res.statusCode), self);
                                                                                   ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/home/chrigu/repos/rabe/rabe-zabbix/node_modules/zabbix-api/index.js:110:84)
    at self.callback (/home/chrigu/repos/rabe/rabe-zabbix/node_modules/request/request.js:129:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at ClientRequest.self.clientErrorHandler (/home/chrigu/repos/rabe/rabe-zabbix/node_modules/request/request.js:239:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
```

The username, password and API endpoint seems to be correctly configured.

**Comment by hairmare** [comment]
Use the `-k` switch to ignore the certificate chain or import the servers keychain to you local certificate store properly.
The error is a bit bad but I haven't found an easy way to make it look nice without doing an additional request just to check for working TLS.

**Comment by paraenggu** [comment]
> The error is a bit bad but I haven't found an easy way to make it look nice without doing an additional request just to check for working TLS.

This would probably have to be fixed [upstream](https://github.com/v2e4lisp/zabbix-api/blob/882db6cf1aa748119636f65a7d49462a5893cdce/index.js#L106-L108) then.

**Comment by paraenggu** [comment]
> Handle type exception from library code

Now I just get `✖ Logging in to Zabbix`, without the helpful message from https://github.com/radiorabe/rabe-zabbix/pull/18/commits/924c2ac4b702a43eaec23e03e3ff7038a47728dc#diff-d7aa037048964f7e91c6f559ae4dd74eR108 if I don't pass the `-k` option

Apart from that, the actual error message seems to be in `err` instead of `err.data` (in this specific case):
`HTTP request error object message: Error: self signed certificate in certificate chain`

**Comment by hairmare** [comment]
It works on my machine 😜 

```
✖ TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/Users/hairmare/Documents/git.repos/rabe/rabe-zabbix/node_modules/zabbix-api/index.js:110:84)
    at self.callback (/Users/hairmare/Documents/git.repos/rabe/rabe-zabbix/node_modules/request/request.js:129:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at ClientRequest.self.clientErrorHandler (/Users/hairmare/Documents/git.repos/rabe/rabe-zabbix/node_modules/request/request.js:239:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
  A request to Zabbix failed and the error wasn't properly handled. --insecure might help in case of TLS errors.
```

Do you have any idea what we could compare to figure out why it isn't working on your box? Maybe it needs a high enough node.js to work properly?

BTW, `✖ Logging in to Zabbix` usually indicates a login failure (which should only trigger *after* TLS negotiation was successful).

**Comment by paraenggu** [comment]
> Do you have any idea what we could compare to figure out why it isn't working on your box? Maybe it needs a high enough node.js to work properly?

I've updated my 6.9.4 node version to the latest LTS which is currently 6.11.1, unfortunately the problem remains.

> BTW, `✖ Logging in to Zabbix` usually indicates a login failure (which should only trigger after TLS negotiation was successful).

Which doesn't seems to be the case here, it works as soon as I add the `-k` option.

Anything else that I should check, maybe some deps?

**Comment by paraenggu** [comment]
After re-installing the node modules (`rm -rf node_modules && npm install`), the type error appears and gets caught properly. So everything looks good now

**Pull request merged**
