### PR TITLE
Feature - CARP

### PR DESCRIPTION
**Pull request by paraenggu**
Monitoring the Common Address Redundancy Protocol (CARP) on FreeBSD systems.

### CODE REVIEW

**Comment by hairmare** [comment]
I would actually prefer this without e8d968e93e4a938e636d0e7bb83093309904b99a. RIght now everything is quite messy pertaining to uppercase vs. lowercase and I think we should default to having everything lowercase.

**Comment by paraenggu** [comment]
> RIght now everything is quite messy pertaining to uppercase vs. lowercase and I think we should default to having everything lowercase.

I don't think it's that bad, we just haven't agreed and documented upon a proper naming convention yet :-)  My original idea was that we use the proper upstream names in titles and template names, like `OpenSSH`, `PostgreSQL` or `ISC DHCP Daemon` for example. IMHO this would suppoort the readability and recognisability. But anyway, I'm open for discussion.

**Comment by hairmare** [comment]
I'd rather we have a directory tree that is easy to work with. IMHO the names of directories in app are more like package names and should be more like `sshd`, `postgresql` and, `dhcpd`. 

Using what you call "proper" is fine in the actual template name and description, the only place where those names IMO don't make sense is in `app/<name>`.

**Comment by paraenggu** [comment]
> the names of directories in app are more like package names and should be more like sshd, postgresql and, dhcpd.

This would imply, that we need another or derived name/variable for directories. Currently the directory name is the same as the apps name (if one follows the [_Adding an app template_](https://github.com/radiorabe/rabe-zabbix/blob/d7be95252f785ecf4f6da188703873ec1c31857b/README.md#adding-an-app-template) section), which was the reason behind e8d968e93e4a938e636d0e7bb83093309904b99a.

I would prefer if we could get to a directory name which is derivable automatically from the app's name (which in turn can contain white spaces and upper case letters, which is already the case with various existing templates).
For this I see five (simple) options:
1. Replace white spaces with underscores (just about the same, as we currently handle XML template names)
   * `${appName// /_}`
   * `My Example App` => `My_Example_App`
2. Replace white spaces with dashes
   * `${appName// /-}`
   * `My Example App` => `My-Example-App`
3. Replace white spaces with underscores or dashes and lower case all letters
   * `${appName// /_}` and `${appName,,}`
   * `My Example App` => `my_example_app`
   * `${appName// /-}` and `${appName,,}`
   * `My Example App` => `my-example-app`
4. Use CamelCase by simply removing the white spaces
   * `${appName// /}`
   * `My Example App` => `MyExampleApp`
5. Fix the make file to handle white spaces

I probably would go with only space replacements (option 1 or 2). What do you think?

After all, I think this is more of a general and independent decision/issue as the the naming in this branch just follows the currently documented way, which also affects [#13](https://github.com/radiorabe/rabe-zabbix/pull/13#issuecomment-312438591). But anyway, I will change the directory name as soon as we come to a conclusion.

**Comment by hairmare** [comment]
> 5. Fix the make file to handle white spaces

We should do 5. this in any case, it's the only proper solution and I should have written the Makefile in a white space safe way from the get go.

Nevertheless, I would like to keep whitespace in file paths at bay. It just makes it easier when interacting with these files in bash and it's defensive vs. 3rd party code interacting with rabe-zabbix. Personally 3b is my fave, irregardless I'm voting for 1. It's the easiest solution and looks the most *Zabbix-idiomatic*.

**Comment by paraenggu** [comment]
> Personally 3b is my fave, irregardless I'm voting for 1. It's the easiest solution and looks the most Zabbix-idiomatic.

Option 1 (_replace white spaces with underscores_) is fine by me, so this PR is ready to be merged then.

I will prepare another PR for updating the bash snippets within the main README according to our decision.

**Pull request merged**
